apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: laravel-circleci
spec:
  template:
    spec:
      containers:
        - image: gcr.io/laravel-circleci-368204/google-cloud-deploy
          ports:
            - containerPort: "80"
          resources:
            limits:
              cpu: "2"
