apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: laravel-circleci
spec:
  template:
    spec:
      containers:
        - image: gcr.io/${STG_GCP_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 2
