apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: laravel-circleci
spec:
  template:
    spec:
      containers:
        - image: gcr.io/$STG_GCP_PROJECT_ID/$GITHUB_REPOSITORY:$GITHUB_SHA-$GITHUB_RUN_NUMBER
          ports:
            - containerPort: "80"
          resources:
            limits:
              cpu: "2"
