apiVersion: v1
kind: Service
metadata:
  name: svc-laravel-circleci
  labels:
    name: svc-laravel-circleci
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30502
  selector:
    name: laravel-circleci
