name: Test and deploy to Cloud Run

on:
  push:
    branches: [ "deploy-ssh" ]
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  SERVER_IP: 35.232.47.148
  SSH_USER: doantv
  REPO_PATH: google-cloud-deploy
jobs:
  deploy-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Git Pull
        run: |
          cd ${{ github.workspace }}
          ssh-keyscan -t rsa $SERVER_IP >> ~/.ssh/known_hosts
          ssh $SSH_USER@$SERVER_IP "cd $REPO_PATH && ls && git fetch && git checkout deploy-ssh && git pull"
          echo "Successfully pulled repo."



