name: Test and deploy to Cloud Run

on:
  push:
    branches: [ "deploy-ssh" ]
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
jobs:
  deploy-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH
        uses: actions/setup-ssh@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}
      - name: SSH to Server
        run: |
          ssh -T doantv@35.232.47.148
          cd $GITHUB_REPOSITORY
          ls



