name: Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job_id:
    # ...
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JSON_KEY_FILE }}'
      - name: Docker build image
        run: docker build --file=dockers/Dockerfile -t ${{ secrets.GITHUB_REPOSITORY }} .

