name: Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
#      - name: gettext install
#        run: apt-get install -qq -y gettext
#      - name: Configure PHP env (STG)
#        run: envsubst < .env.staging > .env
      - name: Google Authentication
        run: |
          echo ${{ secrets.JSON_KEY_FILE }} > ${{ secrets.HOME_PATH }}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${{ secrets.HOME_PATH }}/gcloud-service-key.json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
