name: Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job_id:
    # ...
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        env:
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JSON_KEY_FILE }}'
      - run : echo $GITHUB_RUN_NUMBER
#      - name: Docker build image
#        run: docker build --file=dockers/Dockerfile -t doantv .

