name: Test and deploy to Cloud Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  JSON_KEY_FILE: ${{ secrets.JSON_KEY_FILE }}
  GITHUB_WORKSPACE: ${{ secrets.GITHUB_WORKSPACE }}
  STG_GCP_PROJECT_ID: ${{ secrets.STG_GCP_PROJECT_ID }}
  GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
  GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
  GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
  ENV_STG_DB_PASSWORD: ${{ secrets.ENV_STG_DB_PASSWORD }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
#  deploy-stg:
#    uses: ./.github/workflows/build.yml
#    needs: unit-tests
#    steps:
#      - name: Google Authentication
#        run: |
#          echo $JSON_KEY_FILE > $GITHUB_WORKSPACE/gcloud-service-key.json
#          gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/gcloud-service-key.json
#          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
#      - name: Configure PHP env (STG)
#        run: |
#          envsubst < .env.staging > .env
#      - name: chmod 777 (directory permission adjustment)
#        run: |
#          chmod 777 -R storage
#          chmod 777 -R bootstrap/cache
#      - name: clear laravel config
#        run: php artisan config:clear
#      - name: Docker build image
#        run: docker build --file=dockers/Dockerfile -t $GITHUB_REPOSITORY .
#      - name: Docker push image to GCR
#        run: |
#          docker tag $GITHUB_REPOSITORY gcr.io/$STG_GCP_PROJECT_ID/$GITHUB_REPOSITORY:$GITHUB_SHA-$GITHUB_RUN_NUMBER
#          docker push gcr.io/$STG_GCP_PROJECT_ID/$GITHUB_REPOSITORY:$GITHUB_SHA-$GITHUB_RUN_NUMBER
#          docker tag $GITHUB_REPOSITORY gcr.io/$STG_GCP_PROJECT_ID/$GITHUB_REPOSITORY:latest
#          docker push gcr.io/$STG_GCP_PROJECT_ID/$GITHUB_REPOSITORY:latest
#      - name: Deploy Cloud Run
#        run: |
#          gcloud config set core/project $STG_GCP_PROJECT_ID
#          envsubst < yaml_files/service.yaml > ./service.yaml
#          gcloud run services replace service.yaml --region=asia-east1
#          gcloud run services update laravel-circleci --add-cloudsql-instances=$STG_GCP_PROJECT_ID:asia-east1:laravel-circleci --region=asia-east1

