name: Test and deploy to Cloud Run

on:
  push:
    branches: [ "deploy-ssh" ]
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
jobs:
  deploy-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: 35.232.47.148 # example.com || 8.8.8.8
          SSHKEY: ${{ secrets.SSH_PUBLIC_KEY }} # ----- BEGIN RSA PRIVATE KEY----- ...
          NAME: production
          PORT: 80 # 3000
          USER: doantv # admin
      - run: ssh production ls --help



